### ISSUE TITLE
Compiling GMP fails on ppc64

### ISSUE THREAD

**Issue by markuspf** [gap-system/gap#208]
As far as I can see this is due to the GAP configure passing ABI=64 to GMP's configure.

**Comment by alex-konovalov** [comment]
Should be fixed in #211.

**Comment by markuspf** [comment]
On Tue, Sep 22, 2015 at 06:17:19AM -0700, Alexander Konovalov wrote:
> Should be fixed in #211.

Reopen

#211 does not fix the issue, it just makes it possible to build GAP and the
packaged GMP with the command line option to configure. At the moment the way
to go is to compile --with-gmp=system (and maybe using the system GMP is the
default).

**Comment by fingolfin** [comment]
Could you please give some more details then on what the remaining issue is?
In *theory*, it should be possible to build GAP with its built-in GMP by issuing
```
./configure ABI=FOOBAR && make
```
where FOOBAR must be replaced by a suitable ABI value. Are you saying this is still not working?

Or perhaps this is working, but you'd like GAP to automatically determine the correct ABI value in this case? Or perhaps *not* supplying an ABI to GMP would resolve the issue?

Without access to a ppc64 system, I am afraid I have a hard time debugging this. But if somebody can give me access to one, I'll add it to my TODO list for the new build system (and/or can fix it in the existing build system).

**Comment by fingolfin** [comment]
@markuspf This is needing a response by you...

**Comment by markuspf** [comment]
I will need to dig up my access credentials to the PPC box. I will put this on my TODO list.

**Comment by fingolfin** [comment]
Closing this as out-of-date (and also no update in over a year)
